### ISSUE TITLE
Your app showed an error when started mate!!

### ISSUE THREAD

**Issue by Gitstar-OC** [matinrn/Front-End-Developer-Capstone#1]
![Screenshot 2024-05-11 174241](https://github.com/matinrn/Front-End-Developer-Capstone/assets/152989429/4317b374-78e1-4e6f-a8a4-99ffb72b5919)

**Comment by Gitstar-OC** [comment]
This is a screenshot of the issure

**Comment by matinrn** [comment]
thanks Mate Fixed
